# -*- coding: utf-8 -*-
"""
setup_local.py -- vpoRAG local environment setup for Windows.

Equivalent to running the Ansible Local playbook but runs natively on Windows
without WSL. Ansible requires Unix (fcntl) and cannot run on native Windows Python.

Usage:
    python setup_local.py [options]

Options:
    --repo-root PATH        Path to vpo_rag repo root (default: parent of this script's dir)
    --src-dir PATH          Source documents directory (written to indexers/config.py)
    --tesseract PATH        Tesseract install path (default: auto-detect common locations)
    --search-mode MODE      "Local" or "MCP" for Searches/config.ps1 (default: Local)
    --jira-source SOURCE    "csv", "mysql", or "sql" (default: csv)
    --skip-venv             Skip venv creation and pip install
    --skip-spacy            Skip spaCy model download
    --skip-config           Skip rendering config files
    --force-config          Overwrite existing config files (default: skip if present)
    --python BIN            Python executable to use for venv (default: python)
"""
import argparse, subprocess, sys, os
from pathlib import Path

# ── Jinja2-free template rendering ───────────────────────────────────────────

INDEXER_CONFIG_TEMPLATE = r'''# -*- coding: utf-8 -*-
"""
Local indexer config -- generated by setup_local.py. Do not edit manually.
Re-run: python Setup\Local\setup_local.py
"""

SRC_DIR = r"{src_dir}"
OUT_DIR = r"{out_dir}"

PARA_TARGET_TOKENS       = 512
PARA_OVERLAP_TOKENS      = 128
MIN_CHUNK_TOKENS         = 16
CHUNK_QUALITY_MIN_WORDS  = 10
MAX_ROUTER_SUMMARY_CHARS = 3000
MAX_HIERARCHY_DEPTH      = 6

DEDUPLICATION_INTENSITY = 1
ENABLE_CROSS_FILE_DEDUP = False

ENABLE_CAMELOT = False
ENABLE_OCR     = True
OCR_MIN_IMAGE_SIZE   = (150, 150)
OCR_LANGUAGES        = 'eng'
PARALLEL_OCR_WORKERS = 4
TESSERACT_PATH       = r"{tesseract_path}"

MAX_RELATED_CHUNKS       = 5
MIN_SIMILARITY_THRESHOLD = 0.7
ENABLE_CROSS_REFERENCES  = True
TERM_ALIASES             = {{}}

ENABLE_AUTO_CLASSIFICATION = True
ENABLE_AUTO_TAGGING        = True
MAX_TAGS_PER_CHUNK         = 10

DOC_PROFILES = {{
    "glossary":  ["glossary", "acronym"],
    "slides":    [".pptx"],
    "manual":    ["vertical playbooks", "playbook"],
    "sop":       ["creating tickets", "cross vertical"],
    "queries":   ["splunk", "kibana", "queries"],
    "reference": ["reference", "guide"],
}}

CONTENT_TAGS = {{
    "splunk":          ["splunk", "index=", "sourcetype="],
    "kibana":          ["kibana", "elasticsearch"],
    "troubleshooting": ["troubleshoot", "error", "issue", "problem", "fix"],
    "procedures":      ["procedure", "step", "process", "workflow"],
    "queries":         ["query", "search", "filter"],
    "tickets":         ["ticket", "jira", "incident"],
    "high-split":      ["high split", "hsc", "high-split"],
    "cpe":             ["cpe", "customer premise", "equipment"],
    "entitlements":    ["entitlement", "ace", "clm"],
}}
'''

SEARCHES_CONFIG_TEMPLATE = r'''# Searches/config.ps1 — copy of config.example.ps1, adjusted for your environment.
# config.ps1 is gitignored — never commit it.

# ══════════════════════════════════════════════════════════════════════════════
# PRIMARY SEARCH MODE
# ══════════════════════════════════════════════════════════════════════════════
# "MCP"   — use the centralized LAN server (192.168.1.29).
#            Amazon Q calls search_kb / search_jira MCP tools directly.
#            PowerShell scripts are not used for KB or Jira searches.
# "Local" — use local JSONL files and local CSV/SQL sources.
#            Amazon Q calls Search-DomainAware.ps1 and Search-JiraTickets.ps1
#            via executeBash. No network dependency beyond optional SSMS.
$SEARCH_MODE = "{search_mode}"


# ══════════════════════════════════════════════════════════════════════════════
# MCP MODE SETTINGS  (used when $SEARCH_MODE = "MCP")
# ══════════════════════════════════════════════════════════════════════════════

# URL of the MCP server on the local network.
# Configure in VS Code settings.json under amazonQ.mcp.servers (see mcp_server/README.md).
$MCP_SERVER_URL = "http://192.168.1.29:8000"

# SSH credentials for scripts that connect directly to the MCP server (e.g. Sync-JSONIndex.ps1).
# $MCP_SSH_KEY defaults to $HOME\.ssh\vporag_key if not set.
# Run Ansible\MCP\setup_ssh_key.ps1 once to generate and install the key.
$MCP_SSH_USER = "vpomac"
$MCP_SSH_KEY  = "$HOME\.ssh\vporag_key"

# Shared bearer token — must match AUTH_TOKEN in mcp_server/config.py on the server.
# Leave empty if AUTH_TOKEN is not set on the server (trusted LAN only).
$MCP_AUTH_TOKEN = ""

# ── MCP: KB search defaults ───────────────────────────────────────────────────
# Default search level passed to search_kb(level=...).
# Quick:      4 phases, ~75 chunks  — fast triage
# Standard:   6 phases, ~185 chunks — default, covers 90% of cases
# Deep:       8 phases, ~460 chunks — complex multi-system issues
# Exhaustive: 8 phases, ~920 chunks — root cause / outage analysis
$MCP_SEARCH_LEVEL = "Standard"

# ── MCP: Jira search source ───────────────────────────────────────────────────
# Which data source the MCP server's search_jira tool queries first.
# "mysql" — server-side MySQL on the MCP server (fastest; requires CSV ingest to have run)
# "csv"   — CSV files on the server's Samba share (always available)
# "sql"   — VIDPROD_MAIN via pyodbc (requires server to reach the SQL host on intranet)
# Set in mcp_server/config.py on the server — this value is informational only
# and does not override the server config. Change it there, not here.
$MCP_JIRA_SOURCE = "mysql"   # informational — actual setting lives in mcp_server/config.py


# ══════════════════════════════════════════════════════════════════════════════
# LOCAL MODE SETTINGS  (used when $SEARCH_MODE = "Local")
# ══════════════════════════════════════════════════════════════════════════════

# ── Local: KB path ────────────────────────────────────────────────────────────
# Absolute path to the local JSON output directory.
# Must contain detail\chunks.*.jsonl (built by running indexers/build_index.py locally
# or synced via git pull from the server's committed category files).
$JSON_KB_DIR = "{out_dir}"

# Default search level for Search-DomainAware.ps1.
$JSON_SEARCH_LEVEL = "Standard"

# Override max chunks returned (0 = use level default).
$JSON_MAX_RESULTS = 0

# ── Local: Jira source ────────────────────────────────────────────────────────
# Primary source for Search-JiraTickets.ps1.
# "sqlite" — local SQLite mirror (structuredData/database/jira_local.db) — fastest, works fully offline
#            Sync with: python Setup/sync_local_db.py (requires LAN access to MCP server)
# "csv"    — read local CSV exports from $JIRA_DPS_CSV_DIR / $JIRA_RCA_CSV_DIR
# "sql"    — query VIDPROD_MAIN directly via jira_query.py + pyodbc
#            (requires ODBC Driver 17/18 installed locally and intranet access to VM0PWVPTSPL000)
$JIRA_PRIMARY_SOURCE = "{jira_source}"

# Merge results from ALL sources (LocalDB + CSV + SSMS) and deduplicate by Key.
# When $true, all three sources are queried regardless of which is primary.
$JIRA_SEARCH_ALL_SOURCES = $false

# ── Local: SQLite mirror ──────────────────────────────────────────────────────
# Path to the local SQLite DB file (created automatically on first sync).
$JIRA_LOCAL_DB = "structuredData\database\jira_local.db"
# Remote MySQL on the MCP server — used by sync_local_db.py to pull data into the local SQLite.
# Run: python Setup/sync_local_db.py  (requires LAN access to the MCP server)
$JIRA_REMOTE_MYSQL_HOST = "192.168.1.29"
$JIRA_REMOTE_MYSQL_PORT = 3306
$JIRA_REMOTE_MYSQL_USER = "jira_user"
$JIRA_REMOTE_MYSQL_PASS = ""  # Set to your jira_user MySQL password
$JIRA_REMOTE_MYSQL_DB   = "jira_db"

# ── Local: CSV directories ────────────────────────────────────────────────────
# Paths to local Jira CSV export directories (one per ticket type).
# Used only when $JIRA_PRIMARY_SOURCE = "csv" or $JIRA_SEARCH_ALL_SOURCES = $true.
$JIRA_DPS_CSV_DIR = "structuredData\JiraCSVexport\DPSTRIAGE"
$JIRA_RCA_CSV_DIR = "structuredData\JiraCSVexport\POSTRCA"

# ── Local: SQL connection ─────────────────────────────────────────────────────
# Used only when $JIRA_PRIMARY_SOURCE = "sql".
# Connection settings live in Searches/config.py (Python) — this block is a reminder.
# Requires: ODBC Driver 17 or 18 for SQL Server installed locally.
# Requires: intranet connectivity to VM0PWVPTSPL000 (not available off-network).
# Store credentials once with: python Searches/Connectors/jira_query.py --store-credentials
$JIRA_SQL_NOTE = "Connection settings in Searches/config.py — server VM0PWVPTSPL000, DB VIDPROD_MAIN"
'''

# ── Helpers ───────────────────────────────────────────────────────────────────

def run(cmd, **kwargs):
    print(f"  $ {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, **kwargs)
    if result.returncode != 0:
        sys.exit(f"Command failed (exit {result.returncode})")
    return result


def find_tesseract():
    candidates = [
        Path(os.environ.get("PROGRAMFILES", "C:/Program Files")) / "Tesseract-OCR" / "tesseract.exe",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Tesseract-OCR" / "tesseract.exe",
        Path(os.environ.get("APPDATA", "")) / "Tesseract-OCR" / "tesseract.exe",
    ]
    for p in candidates:
        if p.exists():
            return str(p.parent)
    return str(candidates[1].parent)  # return default even if not found


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    script_dir = Path(__file__).resolve().parent
    default_repo = script_dir.parent.parent  # Setup/Local/ -> Setup/ -> repo root

    p = argparse.ArgumentParser(description="Set up vpoRAG local environment")
    p.add_argument("--repo-root",    default=str(default_repo))
    p.add_argument("--src-dir",      default="")
    p.add_argument("--tesseract",    default="")
    p.add_argument("--search-mode",  default="Local", choices=["Local", "MCP"])
    p.add_argument("--jira-source",  default="csv",   choices=["csv", "mysql", "sql"])
    p.add_argument("--python",       default="python")
    p.add_argument("--skip-venv",    action="store_true")
    p.add_argument("--skip-spacy",   action="store_true")
    p.add_argument("--skip-config",  action="store_true")
    p.add_argument("--force-config", action="store_true")
    args = p.parse_args()

    repo   = Path(args.repo_root).resolve()
    venv   = repo / ".venv"
    pip    = venv / "Scripts" / "pip.exe"
    python = venv / "Scripts" / "python.exe"

    print(f"\n=== vpoRAG Local Setup ===")
    print(f"Repo root : {repo}")
    print(f"Venv      : {venv}\n")

    # ── Step 1: venv + dependencies ──────────────────────────────────────────
    if not args.skip_venv:
        if not (venv / "Scripts" / "activate").exists():
            print("[1/3] Creating virtual environment...")
            run([args.python, "-m", "venv", str(venv)])
        else:
            print("[1/3] Virtual environment already exists — skipping creation.")

        print("      Upgrading pip...")
        run([str(python), "-m", "pip", "install", "--upgrade", "pip", "-q"])

        print("      Installing requirements.txt...")
        run([str(pip), "install", "-r", str(repo / "requirements.txt"), "-q"])
    else:
        print("[1/3] Skipped (--skip-venv).")

    # ── Step 2: spaCy model ───────────────────────────────────────────────────
    if not args.skip_spacy:
        print("[2/3] Downloading spaCy en_core_web_md model...")
        run([str(python), "-m", "spacy", "download", "en_core_web_md"])
    else:
        print("[2/3] Skipped (--skip-spacy).")

    # ── Step 3: render config files ───────────────────────────────────────────
    if not args.skip_config:
        print("[3/3] Rendering config files...")

        src_dir   = args.src_dir or str(repo / "source_docs")
        out_dir   = str(repo / "JSON")
        tesseract = args.tesseract or find_tesseract()

        indexer_cfg = repo / "indexers" / "config.py"
        if indexer_cfg.exists() and not args.force_config:
            print(f"      Skipped (already exists): {indexer_cfg}")
        else:
            indexer_cfg.write_text(
                INDEXER_CONFIG_TEMPLATE.format(
                    src_dir=src_dir, out_dir=out_dir, tesseract_path=tesseract
                ),
                encoding="utf-8",
            )
            print(f"      Written: {indexer_cfg}")

        searches_cfg = repo / "Searches" / "config.ps1"
        if searches_cfg.exists() and not args.force_config:
            print(f"      Skipped (already exists): {searches_cfg}")
        else:
            searches_cfg.write_text(
                SEARCHES_CONFIG_TEMPLATE.format(
                    search_mode=args.search_mode,
                    out_dir=out_dir,
                    jira_source=args.jira_source,
                ),
                encoding="utf-8",
            )
            print(f"      Written: {searches_cfg}")
    else:
        print("[3/3] Skipped (--skip-config).")

    print("\n=== Setup complete ===")
    print(f"Activate venv : {venv}\\Scripts\\Activate.ps1")
    print(f"Run tests     : cd indexers && python tests/test_json_indexer.py")
    print(f"Build index   : cd indexers && python build_index.py\n")


if __name__ == "__main__":
    main()
