[mcp_server]
192.168.1.29

[mcp_server:vars]
ansible_user=vpomac
ansible_ssh_private_key_file=~/.ssh/vporag_key
ansible_become=true
ansible_become_method=sudo
ansible_become_pass="{{ sudo_password }}"
